[package]
name = "stealth_registry"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.16.1"

[dev-dependencies]
snforge_std = "0.57.0"
assert_macros = "2.16.1"

[cairo]
sierra-replace-ids = false

[[target.starknet-contract]]
casm = true
